### PR TITLE
add timeout support to upwork.client

### PR DESCRIPTION
**Pull request by michael-yin**
When I am using python upwork api, I found sometime the program was blocked because of the unstable network. So I think it really make sense to make the client can support timeout setting.

### CODE REVIEW

**Comment by mnovozhylov** [comment]
@michael-yin , thanks for the patch!
it looks good in common, except the default timeout value that shouldn't be so high - the patch will be accepted with the default value set to '3' secs (it should be enough not to kill someone's application)

**Comment by michael-yin** [comment]
Based on my experience, the default timeout for software which have socket connection is usually 30-60 secs by default.

Many developers do not set timeout when using this api, so my suggestion is we can set the default to a high value but not a low value. 

If a programmer met timeout exception, he will first check the network but not change the timeout value to a higher value. Which might make them confused.

**Comment by mnovozhylov** [comment]
Having a high value for timeout option is a really poor practise - if smth goes wrong, such requests will hang out and may overload server's pool

We can accept the patch only with small value - in case someone need a high one, he will be able to setup it in his own code

**Comment by michael-yin** [comment]
Ok, I have modified the code as you asked, I think it can be merged now.
Thanks.

**Comment by mnovozhylov** [comment]
@michael-yin , good job! :+1:

**Pull request merged**
