### PR TITLE
oauth python3 compatibility fixes

### PR DESCRIPTION
**Pull request by frolenkov-nikita**

### CODE REVIEW

**Comment by frolenkov-nikita** [comment]
The unit tests for python3 are failing because they are also not very compatible with python3.

**Comment by szczeles** [comment]
@mnovozhylov Is there any chance to get this PR merged? Current master is not compatible with Python 3, and Python 2 is no longer maintained language (https://pythonclock.org/)

**Comment by aijogja** [comment]
I was tried it, and this is compatible with python 3 `oauth_token  got None` issue

**Comment by mnovozhylov** [comment]
@szczeles , we're working on a fully compatible python 3 library. Please, stay tuned.

**Pull request closed without merging**
